---
- name: Install nginx
  hosts: all
  become: yes
  vars:
    - sourse_file : upstreams.conf
    - dest_file   : /etc/nginx/conf.d   

  tasks:
  - name: Install nginx
    yum: name=nginx state=latest

  - name: Start nginx and make it enable on boot
    service: name=nginx state=started enabled=yes

  - name: Copy upstreams.conf file to conf.d
    copy: src={{sourse_file}} dest={{dest_file}} mode=0555
#    notify: Restart nginx 




#  handlers:
#  - name: Restart nginx
#    service: name=nginx state=reloaded
